### ISSUE TITLE
Bug with pydantic when defining some components

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#150]
When defining some multi-port components, pydantic throws an error.

Code:

```
c = gf.components.crossing()
p = 3
c = gf.add_padding_container(c, default=0, top=p, bottom=p)
df = write_sparameters_meep(c, overwrite=True, animate=False)
```

Traceback:

```
Traceback (most recent call last):
  File "test_write_sparameters_meep.py", line 59, in <module>
    test_sparameterNxN_crossing(None)
  File "test_write_sparameters_meep.py", line 36, in test_sparameterNxN_crossing
    df = write_sparameters_meep(c, overwrite=True, animate=False)
  File "pydantic/decorator.py", line 39, in pydantic.decorator.validate_arguments.validate.wrapper_function
    import itertools
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
    func.__dict__.update(kw)
  File "pydantic/decorator.py", line 200, in pydantic.decorator.ValidatedFunction.execute
    """
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/gmeep/write_sparameters_meep.py", line 404, in write_sparameters_meep
    **settings,
  File "pydantic/decorator.py", line 39, in pydantic.decorator.validate_arguments.validate.wrapper_function
    import itertools
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
    func.__dict__.update(kw)
  File "pydantic/decorator.py", line 200, in pydantic.decorator.ValidatedFunction.execute
    """
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/gmeep/write_sparameters_meep.py", line 270, in sparameter_calculation
    **settings,
  File "pydantic/decorator.py", line 39, in pydantic.decorator.validate_arguments.validate.wrapper_function
    import itertools
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
    func.__dict__.update(kw)
  File "pydantic/decorator.py", line 200, in pydantic.decorator.ValidatedFunction.execute
    """
  File "/home/simbil/Github/gdsfactory/gdsfactory/simulation/gmeep/get_simulation.py", line 131, in get_simulation
    if extend_ports_length
  File "/home/simbil/Github/gdsfactory/gdsfactory/cell.py", line 166, in _cell
    component = func(*args, **kwargs)
  File "pydantic/decorator.py", line 39, in pydantic.decorator.validate_arguments.validate.wrapper_function
    import itertools
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
    func.__dict__.update(kw)
  File "pydantic/decorator.py", line 200, in pydantic.decorator.ValidatedFunction.execute
    """
  File "/home/simbil/Github/gdsfactory/gdsfactory/components/extension.py", line 154, in extend_ports
    layer=port.layer,
  File "/home/simbil/Github/gdsfactory/gdsfactory/cell.py", line 166, in _cell
    component = func(*args, **kwargs)
  File "pydantic/decorator.py", line 39, in pydantic.decorator.validate_arguments.validate.wrapper_function
    import itertools
  File "pydantic/decorator.py", line 132, in pydantic.decorator.ValidatedFunction.call
    func.__module__ = getattr(self, 'module', callermodule)
  File "pydantic/decorator.py", line 129, in pydantic.decorator.ValidatedFunction.init_model_instance
    callermodule = '?'
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Straight
cross_section
  none is not an allowed value (type=type_error.none.not_allowed)

Elapsed run time = 0.0665 s
```

Also happens with other non-straight components like coupler

**Comment by simbilod** [comment]
Tentatively, it seems the issue occurs when `get_simulation` attempts to `extend_ports` in `components.extension.py`. This was changed recently in commit ec8b2c3 (https://github.com/simbilod/gdsfactory/commit/ec8b2c3ab5c83cbd195dad1629ed169571fd1adc)
