### ISSUE TITLE
component.show() not working in IPython

### ISSUE THREAD

**Issue by fp-matt** [gdsfactory/gdsfactory#2782]
**Describe the bug**
When trying to debug my layout code, I have frequently used `component.show()` to view subcomponents using my IDE's IPython console. With the recent integration of KFactory into GDSFactory, it seems like this doesn't work anymore. From what I can tell, it's trying to create a couple files in my Python project's file structure, and then trying to write a layout file to that directory using the name of the file that called it, but fails to open the file for some reason (maybe since the filename has `<` and `>` characters in it?). Additionally, I have have no idea why, but sometimes it seems to try to write the file as a .oas file, and sometimes as a .gds file. I don't know if this part is reproducible with my sample code, but I have seen it come up when using my layout code.

**To Reproduce**
some sample code:

```
import gdsfactory as gf


def xs(width: float = 500) -> gf.CrossSection:
    return gf.cross_section.cross_section(width=width,
                                          layer=(1, 0),
                                          main_section_name="rect_waveguide",
                                          )


@gf.cell
def wont_show_in_ipython(length: float = 1500,
              width: float = 500,
              ) -> gf.Component:

    c = gf.Component("ridge_with_broken_extrusion")

    p = gf.path.straight(length=length)

    c << gf.path.extrude(p,
                         cross_section=xs(width=width),
                         )

    return c


if __name__ == "__main__":
    c = wont_show_in_ipython()
    c.show()
```

which works fine if you run it like normal, but if you put a breakpoint at `c.show()` and then enter `c.show()` to the IPython console attached to the debugger, I get this traceback:

```
Traceback (most recent call last):
  File "C:\[...]\envs\MaskLayout\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-86df1d1172c0>", line 1, in <module>
    c.show()
  File "C:\[...]\envs\MaskLayout\Lib\site-packages\kfactory\kcell.py", line 1095, in show
    show(
  File "C:\[...]\envs\MaskLayout\Lib\site-packages\kfactory\kcell.py", line 7098, in show
    layout.write(tf, save_options)
  File "C:\[...]\envs\MaskLayout\Lib\site-packages\kfactory\kcell.py", line 1488, in write
    self._kdb_cell.write(str(filename), save_options)
RuntimeError: Unable to open file: C:\Users\[user]\AppData\Local\Temp\<ipython-input-1-86df1d1172c0>.gds (errno=22) in Cell.write
```

**Expected behavior**
To be able to open components in KLayout using KLive from IPython console

**Suggested fix**
Maybe default the filename to `Unnamed` with a unique identifier?

**Comment by joamatab** [comment]
What version of klayout are you using?

You need to update klayout to a somewhat recent version

**Comment by fp-matt** [comment]
I am currently using KLayout v0.29.0

**Comment by joamatab** [comment]
What version on klive?

**Comment by fp-matt** [comment]
@joamatab I have klive v0.3.2

**Comment by doddgray** [comment]
I also ran into this issue after upgrading to v8 and needed to find a quick fix. 

To do this I added a special case in `kfactory.kcell` to recognize calls from IPython kernels in the handling of `name` and used `tempfile` paths for the OAS files in that scenario. It seems to fix the issue, at least interactive sessions can stream GDS data to KLayout again.  Maybe not the right way to do this in the long run.

In a local branch I modified the code here:
https://github.com/gdsfactory/kfactory/blob/2e8612db42b7da756ff84eafd6ab9a667d695de8/src/kfactory/kcell.py#L7577
to look like
```python
    # Find the file that calls stack
    try:
        stk = inspect.getouterframes(inspect.currentframe())
        frame = stk[2]
        frame_filename_stem = Path(frame.filename).stem
        if frame_filename_stem.startswith("<ipython-input"):    # Case 1: IPython Kernel call
            ipython_shell_id = frame_filename_stem.rstrip(">").split("-")[-1]
            name = f"ipython-{ipython_shell_id}"
        else:                                                                              #  Case 2: Not IPython Kernel call
            if frame.function != "<module>":
                name = frame_filename_stem + "_" + frame.function
            else:
                name = frame_filename_stem
```

and the code here:
https://github.com/gdsfactory/kfactory/blob/2e8612db42b7da756ff84eafd6ab9a667d695de8/src/kfactory/kcell.py#L7659C1-L7661C63
to look like:
```python
                if wtd is not None:
                    if name.startswith("ipython-"):
                        root = Path(tempfile.gettempdir()) / "gdsfactory"
                    else:
                        root = Path(wtd) / "build/gds"
                    root.mkdir(parents=True, exist_ok=True)
                    tf = root / Path(name).with_suffix(".oas")
```

I'm happy to create a pull request, but not sure if this is how the maintainers want to approach this.

**Comment by sebastian-goeldi** [comment]
@doddgray seems reasonable to me. I am totally on board with doing this at least from the quick read through I did. I think in general it might also be better in the ipython (and probably shell) case to use a temp file. My motivation behind the build folder was so that there is traceability (and we don't need to care too much about tempfiles as they can be nasty if we or python clean up too fast). As it will allow you to go back and inspect the gds in case something went wrong or you accidentally close a gds which takes some time to build, etc.

Feel free to open the PR on kfactory. I am the main maintainer over there and @joamatab is the one that finds most of the bugs ^^

I

**Comment by joamatab** [comment]
Verified against the current kfactory-backed `show()` implementation: call frames whose filename starts with `<ipython-input` are explicitly mapped to the safe name `ipython`; other frame-derived names pass through `clean_name`. The invalid Windows path from the report is therefore no longer generated. Closing as resolved upstream.
