### ISSUE TITLE
component.show() not working when using watch

### ISSUE THREAD

**Issue by SF73** [gdsfactory/gdsfactory#2863]
**Describe the bug**
It seems that component.show() get a wrong (invalid) filename when I use `gf watch`

**To Reproduce**
 
If I try to run the basic [polygon example](https://gdsfactory.github.io/gdsfactory/notebooks/00_geometry.html#polygons) from the doc

```py
import gdsfactory as gf

c = (
    gf.Component()
)  # Create a blank component (essentially an empty GDS cell with some special features)
p1 = c.add_polygon([(-8, -6), (6, 8), (7, 17), (9, 5)], layer=(1, 0))
# c.write_gds("demo.gds")  # write it to a GDS file. You can open it in klayout.
c.show()  # show it in klayout
```
It's working perfectly when I execute the file but it fails when I use `gf watch --path .` 
I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\[user]\Documents\Python\test-gdsfactory\.venv\lib\site-packages\gdsfactory\watch.py", line 142, in get_component
    exec(filepath.read_text(), d, d)
  File "<string>", line 9, in <module>
  File "C:\Users\[user]\Documents\Python\test-gdsfactory\.venv\lib\site-packages\kfactory\kcell.py", line 1127, in show
    show(
  File "C:\Users\[user]\Documents\Python\test-gdsfactory\.venv\lib\site-packages\kfactory\kcell.py", line 7634, in show
    layout.write(tf, save_options)
  File "C:\Users\[user]\Documents\Python\test-gdsfactory\.venv\lib\site-packages\kfactory\kcell.py", line 1523, in write
    self._kdb_cell.write(str(filename), save_options)
RuntimeError: Unable to open file: C:\Users\[user]\AppData\Local\Temp\<string>.gds (errno=22) in Cell.write
Unable to open file: C:\Users\[user]\AppData\Local\Temp\<string>.gds (errno=22) in Cell.write
```

I use KLayout 0.29.1 with klive 0.3.2.

At this location the stack does not contain the filename if 
https://github.com/gdsfactory/kfactory/blob/6ae88aa1c35b2143146e3fe1f0a7261e3dad53dc/src/kfactory/kcell.py#L7535

**Expected behavior**
What would you like to happen?

**Suggested fix**
How could we fix the bug?

**Comment by joamatab** [comment]
Verified against the current kfactory-backed implementation: `show()` now passes stack-derived filenames through `clean_name` before constructing the temporary layout path. In particular, the watcher's historical `<string>` frame sanitizes to `string`, so the Windows-invalid `<string>.gds` path is no longer produced. Closing as fixed by the backend migration.
