### ISSUE TITLE
.dmove() (and .move()) not compatible with Port or DPoint arguments

### ISSUE THREAD

**Issue by karl-johnson** [gdsfactory/gdsfactory#3199]
**Is your feature request related to a problem? Please describe.**

My layouts using gdsfactory7 frequently used Ports as one of the coordinates in .move() operations. I am migrating to gdsfactory8 and was surprised to get this error for both .move() (which I understand will change units in the next update) and .dmove():

```import gdsfactory as gf
c = gf.Component()
p = gf.path.straight(10)
s = gf.Section(
        width= 0.5,
        layer= (1,0),
        port_names=("o1", "o2"))
xs = gf.CrossSection(sections = [s])
wg = c << gf.path.extrude(p = p, cross_section = xs)
wg.move(wg.ports['o1'], (5,5))
```
```
 File ~\anaconda3\Lib\site-packages\kfactory\kcell.py:6977 in dmove
    float(destination[0] - origin[0]), float(destination[1] - origin[1])

TypeError: 'Port' object is not subscriptable
```

Using .center to access the port's coordinate as a tuple is workaround which I admit isn't too bad:
```wg.dmove(wg.ports['o1'].center, (5,5))```

However, some other coordinate-returning commands don't work with move, as they return a DPoint (instead of a tuple):
`wg.dmove(wg.center, (5,5))` or `wg.dmove(wg.dcenter, (5,5))` 
`TypeError: 'DPoint' object is not subscriptable`

My current workaround for that one is the following, which is clunky (is there any simpler method to convert a DPoint to a tuple?):
`wg.dmove((wg.dcenter.x, wg.dcenter.y), (5,5))`

I am aware of the align and connect commands, and I use those where possible instead of doing a move myself. However, there are numerous circumstances where using a Port or bounding box center as the origin of a move really helps to arrange things.

**Describe the solution you'd like + my questions**
1. Note in the migration guidelines in the documentation which commands don't support Ports as arguments anymore, if there are others.
2. Is it intended for some functions to use tuples for coordinates and some functions to use DPoints? If so, under what conditions are each used, and why is this?
3. If the above is not intended, it seems like any function which takes a coordinate as an argument should be updated so it can accept a DPoint object (and being able to accept a Port object would be a nice quality-of-life addition too!).

**Comment by tvt173** [comment]
this is also driving me crazy. it looks like this function is inherited from `KCell`. @sebastian-goeldi any reason not to change this in kfactory?

**Comment by sebastian-goeldi** [comment]
should be a non-issue in gdsfactory9 now as all the classes use the same geometric class as a base

**Comment by ordicker** [comment]
I got the same problem on 9.5.4
simple example:
```python
import gdsfactory as gf
import matplotlib.pyplot as plt
import meep as mp
import numpy as np
from gdsfactory.generic_tech import get_generic_pdk
from meep import MaterialGrid, Medium, Vector3, Volume
from meep.adjoint import (
    DesignRegion,
    get_conic_radius_from_eta_e,
)

import gplugins
import gplugins.gmeep as gm
from gplugins.gmeep.get_simulation import get_simulation

gf.config.rich_output()
PDK = get_generic_pdk()
PDK.activate()

design_region_width = 2.5
design_region_height = 3.5

eta_e = 0.55
minimum_length = 0.1
filter_radius = get_conic_radius_from_eta_e(minimum_length, eta_e)
eta_i = 0.5
eta_d = 1 - eta_e

resolution = 20
design_region_resolution = int(5 * resolution)

Nx = int(design_region_resolution * design_region_width)
Ny = int(design_region_resolution * design_region_height)

pml_size = 1.0
waveguide_length = 1.5
waveguide_width = 0.5
Sx = 2 * pml_size + 2 * waveguide_length + design_region_width
Sy = 2 * pml_size + design_region_height + 0.5
cell_size = (Sx, Sy)

SiO2 = Medium(index=1.44)
Si = Medium(index=3.4)

design_variables = MaterialGrid(Vector3(Nx, Ny), SiO2, Si, grid_type="U_MEAN")
design_region = DesignRegion(
    design_variables,
    volume=Volume(
        center=Vector3(),
        size=Vector3(design_region_width, design_region_height, 0),
    ),
)

c = gf.Component("mmi1x2")

arm_separation = 1.0
straight1 = c << gf.components.taper(6.5, width2=1)
straight1.dmove(straight1.ports["o2"], (-design_region_width / 2.0, 0))
```
and got this error: 
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda/envs/pmp/lib/python3.11/site-packages/kfactory/geometry.py", line 650, in dmove
    kdb.DCplxTrans(destination[0] - origin[0], destination[1] - origin[1])
                                    ~~~~~~^^^
TypeError: 'DPort' object is not subscriptable
`
