### ISSUE TITLE
Usage of unlock method is not delcared in the documents

### ISSUE THREAD

**Issue by Lingfsama** [gdsfactory/gdsfactory#538]
import gdsfactory as gf
from gdsfactory.component import Component
import pylab
from regex import D

layer_wg = (1,0)
layer_pad = (2,0)

DC_name = 'Direction_coupler'
Delay_name = 'Delay_line'
DC_test_name = 'DC_Cascaded'
Bend_test = 'Bends'
Loss_test = 'Loss'

@gf.cell
def Die(die_name):
    D=gf.components.die(
    size = (5000,10000),
    street_length=1000,
    street_width=100,
    die_name=die_name,
    text_size=100,
    text_location='SW',
    layer=layer_wg
    )
    D << gf.import_gds('nazca_export.gds')
    return D

gf.Component.unlock()
C = Die('test',cache=False)

Something went wrong when I tried to modify the components that I want to use in my layout.
The gf.Component.unlock() doesn't work for my locked components.
At first I tried and it succeeded but these errors reported right after I modified the function.

2022-07-13 17:04:43.707 | INFO     | gdsfactory.config:<module>:52 - Load 'C:\\Users\\liuli\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\gdsfactory' 5.5.9
Traceback (most recent call last):
  File "c:\Users\liuli\OneDrive\\u684c\u9762\LF\GDS_Shijia_Library.py", line 37, in <module>
    C = Die('test',cache=False)
  File "C:\Users\liuli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gdsfactory\cell.py", line 151, in _cell
    component = func(*args, **kwargs)
  File "pydantic\decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    from contextlib import _GeneratorContextManager
  File "pydantic\decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
    
  File "pydantic\decorator.py", line 201, in pydantic.decorator.ValidatedFunction.execute
    Fix args and kwargs to be consistent with the signature
  File "c:\Users\liuli\OneDrive\\u684c\u9762\LF\GDS_Shijia_Library.py", line 32, in Die
    D << gf.import_gds('nazca_export.gds')
  File "C:\Users\liuli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\phidl\device_layout.py", line 1106, in __lshift__
    return self.add_ref(element)
  File "C:\Users\liuli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gdsfactory\component.py", line 696, in add_ref
    self.add(ref)
  File "C:\Users\liuli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gdsfactory\component.py", line 629, in add
    self.is_unlocked()
  File "C:\Users\liuli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gdsfactory\component.py", line 608, in is_unlocked
    raise MutabilityError(
gdsfactory.component.MutabilityError: You cannot modify locked Component 'die_db75779b'. You need to make a copy of this Component or create a new Component and add a reference to it. Changing a component after creating it can be dangerous as it will affect all of its instances. You can unlock it (at your own risk) by calling `unlock()`

**Comment by joamatab** [comment]
thank you for your question @Lingfsama 

I improved the error message to be more clear

```
MutabilityError: Component 'die_d0cf1598' cannot be modified as it is already on cache.
You cannot modify a Component after creation. Changing a component after creation it can be dangerous as it will affect all of its instances.

Create a new Component and add a reference to it.

For example:

# BAD
c = gf.components.bend_euler()
c.add_ref(gf.components.mzi())

# GOOD
c = gf.Component()
c.add_ref(gf.components.bend_euler())
c.add_ref(gf.components.mzi())

```


This is how I would fix the issue you had

```
import gdsfactory as gf
from gdsfactory.component import Component
import pylab
from regex import D

layer_wg = (1, 0)
layer_pad = (2, 0)

DC_name = "Direction_coupler"
Delay_name = "Delay_line"
DC_test_name = "DC_Cascaded"
Bend_test = "Bends"
Loss_test = "Loss"


# add nazca_export file to be able to reproduce issue
c = gf.components.mzi()
c.write_gds('nazca_export.gds')


@gf.cell
def Die(die_name):
    D = gf.Component()
    D << gf.components.die(
        size=(5000, 10000),
        street_length=1000,
        street_width=100,
        die_name=die_name,
        text_size=100,
        text_location="SW",
        layer=layer_wg,
    )
    D << gf.import_gds("nazca_export.gds")
    return D


C = Die("test", cache=False)

```

You can also watch this video

https://www.youtube.com/watch?v=zCOvdSFlHGk

let me know what you think

**Comment by Lingfsama** [comment]
Hi,
Thanks for your answer.
I also tried
D.unlock() as for debug mode and 
I comment it out when the design is fixed.
Best regards,
