### ISSUE TITLE
type checking recursive_netlist for sax plugin

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#971]
**Describe the bug**

pydantic throws a `ValidationError error` when inputing `c.get_netlist_recursive()` netlist in `sax` when the component has references to components imported with `import_gds() `

**To Reproduce**

Minimal example:

```
# Minimal setup
import gdsfactory as gf
import numpy as np
import sax

def straight(wl=1.55, length=252, neff=1.575, loss=0.371) -> sax.SDict:
    """Straight model."""
    phase = 2 * np.pi * neff * length / wl
    amplitude = np.asarray(10 ** (-loss * length * 1E-4 / 20), dtype=complex)
    return sax.reciprocal({("o1", "o2"): amplitude * np.exp(1j * phase)})

models = {"straight": straight}
wl = np.linspace(1.5,1.6)

# This runs
r1 = gf.components.straight()
c = gf.Component()

c << r1

netlist = c.get_netlist_recursive()
circuit2, _ = sax.circuit(netlist=netlist, models=models)
S = circuit2(wl=wl)

# This results in error
r1 = gf.components.straight()
r1.write_gds("test.gds")

c = gf.Component()

load_r1 = gf.import_gds("test.gds")
c << load_r1

netlist = c.get_netlist_recursive()
circuit2, _ = sax.circuit(netlist=netlist, models=models)
S = circuit2(wl=wl)
```

Error:

```
Traceback (most recent call last):
  File "/home/bilodeaus/Github/testing/gdsfactory/venv/lib/python3.10/site-packages/sax/circuit.py", line 270, in _validate_net
    netlist = Netlist.parse_obj(netlist)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Netlist
instances
  field required (type=value_error.missing)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bilodeaus/Github/testing/gdsfactory/issue_netlist.py", line 35, in <module>
    circuit2, _ = sax.circuit(netlist=netlist, models=models)
  File "/home/bilodeaus/Github/testing/gdsfactory/venv/lib/python3.10/site-packages/sax/circuit.py", line 172, in circuit
    recnet: RecursiveNetlist = _validate_net(netlist)
  File "/home/bilodeaus/Github/testing/gdsfactory/venv/lib/python3.10/site-packages/sax/circuit.py", line 272, in _validate_net
    netlist = RecursiveNetlist.parse_obj(netlist)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RecursiveNetlist
__root__ -> Unnamed_e2688391 -> instances -> straight_1 -> component
  field required (type=value_error.missing)
```

**Expected behavior**

Components loaded with import_gds or defined from scratch should behave the same when put in the `sax` plugin

**Suggested fix**

The error is in `sax`, but could (or should?) be handled by suitable preprocessing of netlists or components in `gdsfactory`

@flaport @joamatab

**Comment by joamatab** [comment]
i think this was fixed

https://gdsfactory.github.io/gplugins/notebooks/sax_01_sax.html
